version: '3'
services:
  contamiki:
    container_name: contamiki
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=un_secreto_muy_seguro_y_largo_cambialo
      - APP_URL=https://conta.mafede.i234.me
    volumes:
      - /volume1/docker/contamiki/data:/app/data
