version: '3'
services:
  contamiki:
    container_name: contamiki
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
# Ajusta la ruta de abajo según tu NAS
      - /volume1/docker/contamiki/data:/app/data
      #- /volume1/docker/contamiki/.env:/app/.env
